package emojis.v120;

import java.util.HashMap;

public class SmileysPeople {
    // 😃 Smileys & People
    public static HashMap<String, String> get() {
        String[] keys = new String[] {
                "\ud83d\ude00",
                "\ud83d\ude03",
                "\ud83d\ude04",
                "\ud83d\ude01",
                "\ud83d\ude06",
                "\ud83d\ude05",
                "\ud83e\udd23",
                "\ud83d\ude02",
                "\ud83d\ude42",
                "\ud83d\ude43",
                "\ud83d\ude09",
                "\ud83d\ude0a",
                "\ud83d\ude07",
                "\ud83e\udd70",
                "\ud83d\ude0d",
                "\ud83e\udd29",
                "\ud83d\ude18",
                "\ud83d\ude17",
                "\u263a",
                "\ud83d\ude1a",
                "\ud83d\ude19",
                "\ud83d\ude0b",
                "\ud83d\ude1b",
                "\ud83d\ude1c",
                "\ud83e\udd2a",
                "\ud83d\ude1d",
                "\ud83e\udd11",
                "\ud83e\udd17",
                "\ud83e\udd2d",
                "\ud83e\udd2b",
                "\ud83e\udd14",
                "\ud83e\udd10",
                "\ud83e\udd28",
                "\ud83d\ude10",
                "\ud83d\ude11",
                "\ud83d\ude36",
                "\ud83d\ude0f",
                "\ud83d\ude12",
                "\ud83d\ude44",
                "\ud83d\ude2c",
                "\ud83e\udd25",
                "\ud83d\ude0c",
                "\ud83d\ude14",
                "\ud83d\ude2a",
                "\ud83e\udd24",
                "\ud83d\ude34",
                "\ud83d\ude37",
                "\ud83e\udd12",
                "\ud83e\udd15",
                "\ud83e\udd22",
                "\ud83e\udd2e",
                "\ud83e\udd27",
                "\ud83e\udd75",
                "\ud83e\udd76",
                "\ud83e\udd74",
                "\ud83d\ude35",
                "\ud83e\udd2f",
                "\ud83e\udd20",
                "\ud83e\udd73",
                "\ud83d\ude0e",
                "\ud83e\udd13",
                "\ud83e\uddd0",
                "\ud83d\ude15",
                "\ud83d\ude1f",
                "\ud83d\ude41",
                "\u2639",
                "\ud83d\ude2e",
                "\ud83d\ude2f",
                "\ud83d\ude32",
                "\ud83d\ude33",
                "\ud83e\udd7a",
                "\ud83d\ude26",
                "\ud83d\ude27",
                "\ud83d\ude28",
                "\ud83d\ude30",
                "\ud83d\ude25",
                "\ud83d\ude22",
                "\ud83d\ude2d",
                "\ud83d\ude31",
                "\ud83d\ude16",
                "\ud83d\ude23",
                "\ud83d\ude1e",
                "\ud83d\ude13",
                "\ud83d\ude29",
                "\ud83d\ude2b",
                "\ud83d\ude24",
                "\ud83d\ude21",
                "\ud83d\ude20",
                "\ud83e\udd2c",
                "\ud83d\ude08",
                "\ud83d\udc7f",
                "\ud83d\udc80",
                "\u2620",
                "\ud83d\udca9",
                "\ud83e\udd21",
                "\ud83d\udc79",
                "\ud83d\udc7a",
                "\ud83d\udc7b",
                "\ud83d\udc7d",
                "\ud83d\udc7e",
                "\ud83e\udd16",
                "\ud83d\ude3a",
                "\ud83d\ude38",
                "\ud83d\ude39",
                "\ud83d\ude3b",
                "\ud83d\ude3c",
                "\ud83d\ude3d",
                "\ud83d\ude40",
                "\ud83d\ude3f",
                "\ud83d\ude3e",
                "\ud83d\udc8b",
                "\ud83d\udc4b",
                "\ud83e\udd1a",
                "\ud83d\udd90",
                "\u270b",
                "\ud83d\udd96",
                "\ud83d\udc4c",
                "\u270c",
                "\ud83e\udd1e",
                "\ud83e\udd1f",
                "\ud83e\udd18",
                "\ud83e\udd19",
                "\ud83d\udc48",
                "\ud83d\udc49",
                "\ud83d\udc46",
                "\ud83d\udd95",
                "\ud83d\udc47",
                "\u261d",
                "\ud83d\udc4d",
                "\ud83d\udc4e",
                "\u270a",
                "\ud83d\udc4a",
                "\ud83e\udd1b",
                "\ud83e\udd1c",
                "\ud83d\udc4f",
                "\ud83d\ude4c",
                "\ud83d\udc50",
                "\ud83e\udd32",
                "\ud83e\udd1d",
                "\ud83d\ude4f",
                "\u270d",
                "\ud83d\udc85",
                "\ud83e\udd33",
                "\ud83d\udcaa",
                "\ud83e\uddb5",
                "\ud83e\uddb6",
                "\ud83d\udc42",
                "\ud83d\udc43",
                "\ud83e\udde0",
                "\ud83e\uddb7",
                "\ud83e\uddb4",
                "\ud83d\udc40",
                "\ud83d\udc41",
                "\ud83d\udc45",
                "\ud83d\udc44",
                "\ud83d\udc76",
                "\ud83e\uddd2",
                "\ud83d\udc66",
                "\ud83d\udc67",
                "\ud83e\uddd1",
                "\ud83d\udc71",
                "\ud83d\udc68",
                "\ud83e\uddd4",
                "\ud83d\udc68\u200d\ud83e\uddb0",
                "\ud83d\udc68\u200d\ud83e\uddb1",
                "\ud83d\udc68\u200d\ud83e\uddb3",
                "\ud83d\udc68\u200d\ud83e\uddb2",
                "\ud83d\udc69",
                "\ud83d\udc69\u200d\ud83e\uddb0",
                "\ud83d\udc69\u200d\ud83e\uddb1",
                "\ud83d\udc69\u200d\ud83e\uddb3",
                "\ud83d\udc69\u200d\ud83e\uddb2",
                "\ud83d\udc71\u200d\u2640\ufe0f",
                "\ud83d\udc71\u200d\u2642\ufe0f",
                "\ud83e\uddd3",
                "\ud83d\udc74",
                "\ud83d\udc75",
                "\ud83d\ude4d",
                "\ud83d\ude4d\u200d\u2642\ufe0f",
                "\ud83d\ude4d\u200d\u2640\ufe0f",
                "\ud83d\ude4e",
                "\ud83d\ude4e\u200d\u2642\ufe0f",
                "\ud83d\ude4e\u200d\u2640\ufe0f",
                "\ud83d\ude45",
                "\ud83d\ude45\u200d\u2642\ufe0f",
                "\ud83d\ude45\u200d\u2640\ufe0f",
                "\ud83d\ude46",
                "\ud83d\ude46\u200d\u2642\ufe0f",
                "\ud83d\ude46\u200d\u2640\ufe0f",
                "\ud83d\udc81",
                "\ud83d\udc81\u200d\u2642\ufe0f",
                "\ud83d\udc81\u200d\u2640\ufe0f",
                "\ud83d\ude4b",
                "\ud83d\ude4b\u200d\u2642\ufe0f",
                "\ud83d\ude4b\u200d\u2640\ufe0f",
                "\ud83d\ude47",
                "\ud83d\ude47\u200d\u2642\ufe0f",
                "\ud83d\ude47\u200d\u2640\ufe0f",
                "\ud83e\udd26",
                "\ud83e\udd26\u200d\u2642\ufe0f",
                "\ud83e\udd26\u200d\u2640\ufe0f",
                "\ud83e\udd37",
                "\ud83e\udd37\u200d\u2642\ufe0f",
                "\ud83e\udd37\u200d\u2640\ufe0f",
                "\ud83d\udc68\u200d\u2695\ufe0f",
                "\ud83d\udc69\u200d\u2695\ufe0f",
                "\ud83d\udc68\u200d\ud83c\udf93",
                "\ud83d\udc69\u200d\ud83c\udf93",
                "\ud83d\udc68\u200d\ud83c\udfeb",
                "\ud83d\udc69\u200d\ud83c\udfeb",
                "\ud83d\udc68\u200d\u2696\ufe0f",
                "\ud83d\udc69\u200d\u2696\ufe0f",
                "\ud83d\udc68\u200d\ud83c\udf3e",
                "\ud83d\udc69\u200d\ud83c\udf3e",
                "\ud83d\udc68\u200d\ud83c\udf73",
                "\ud83d\udc69\u200d\ud83c\udf73",
                "\ud83d\udc68\u200d\ud83d\udd27",
                "\ud83d\udc69\u200d\ud83d\udd27",
                "\ud83d\udc68\u200d\ud83c\udfed",
                "\ud83d\udc69\u200d\ud83c\udfed",
                "\ud83d\udc68\u200d\ud83d\udcbc",
                "\ud83d\udc69\u200d\ud83d\udcbc",
                "\ud83d\udc68\u200d\ud83d\udd2c",
                "\ud83d\udc69\u200d\ud83d\udd2c",
                "\ud83d\udc68\u200d\ud83d\udcbb",
                "\ud83d\udc69\u200d\ud83d\udcbb",
                "\ud83d\udc68\u200d\ud83c\udfa4",
                "\ud83d\udc69\u200d\ud83c\udfa4",
                "\ud83d\udc68\u200d\ud83c\udfa8",
                "\ud83d\udc69\u200d\ud83c\udfa8",
                "\ud83d\udc68\u200d\u2708\ufe0f",
                "\ud83d\udc69\u200d\u2708\ufe0f",
                "\ud83d\udc68\u200d\ud83d\ude80",
                "\ud83d\udc69\u200d\ud83d\ude80",
                "\ud83d\udc68\u200d\ud83d\ude92",
                "\ud83d\udc69\u200d\ud83d\ude92",
                "\ud83d\udc6e",
                "\ud83d\udc6e\u200d\u2642\ufe0f",
                "\ud83d\udc6e\u200d\u2640\ufe0f",
                "\ud83d\udd75",
                "\ud83d\udd75\ufe0f\u200d\u2642\ufe0f",
                "\ud83d\udd75\ufe0f\u200d\u2640\ufe0f",
                "\ud83d\udc82",
                "\ud83d\udc82\u200d\u2642\ufe0f",
                "\ud83d\udc82\u200d\u2640\ufe0f",
                "\ud83d\udc77",
                "\ud83d\udc77\u200d\u2642\ufe0f",
                "\ud83d\udc77\u200d\u2640\ufe0f",
                "\ud83e\udd34",
                "\ud83d\udc78",
                "\ud83d\udc73",
                "\ud83d\udc73\u200d\u2642\ufe0f",
                "\ud83d\udc73\u200d\u2640\ufe0f",
                "\ud83d\udc72",
                "\ud83e\uddd5",
                "\ud83e\udd35",
                "\ud83d\udc70",
                "\ud83e\udd30",
                "\ud83e\udd31",
                "\ud83d\udc7c",
                "\ud83c\udf85",
                "\ud83e\udd36",
                "\ud83e\uddb8",
                "\ud83e\uddb8\u200d\u2642\ufe0f",
                "\ud83e\uddb8\u200d\u2640\ufe0f",
                "\ud83e\uddb9",
                "\ud83e\uddb9\u200d\u2642\ufe0f",
                "\ud83e\uddb9\u200d\u2640\ufe0f",
                "\ud83e\uddd9",
                "\ud83e\uddd9\u200d\u2642\ufe0f",
                "\ud83e\uddd9\u200d\u2640\ufe0f",
                "\ud83e\uddda",
                "\ud83e\uddda\u200d\u2642\ufe0f",
                "\ud83e\uddda\u200d\u2640\ufe0f",
                "\ud83e\udddb",
                "\ud83e\udddb\u200d\u2642\ufe0f",
                "\ud83e\udddb\u200d\u2640\ufe0f",
                "\ud83e\udddc",
                "\ud83e\udddc\u200d\u2642\ufe0f",
                "\ud83e\udddc\u200d\u2640\ufe0f",
                "\ud83e\udddd",
                "\ud83e\udddd\u200d\u2642\ufe0f",
                "\ud83e\udddd\u200d\u2640\ufe0f",
                "\ud83e\uddde",
                "\ud83e\uddde\u200d\u2642\ufe0f",
                "\ud83e\uddde\u200d\u2640\ufe0f",
                "\ud83e\udddf",
                "\ud83e\udddf\u200d\u2642\ufe0f",
                "\ud83e\udddf\u200d\u2640\ufe0f",
                "\ud83d\udc86",
                "\ud83d\udc86\u200d\u2642\ufe0f",
                "\ud83d\udc86\u200d\u2640\ufe0f",
                "\ud83d\udc87",
                "\ud83d\udc87\u200d\u2642\ufe0f",
                "\ud83d\udc87\u200d\u2640\ufe0f",
                "\ud83d\udeb6",
                "\ud83d\udeb6\u200d\u2642\ufe0f",
                "\ud83d\udeb6\u200d\u2640\ufe0f",
                "\ud83c\udfc3",
                "\ud83c\udfc3\u200d\u2642\ufe0f",
                "\ud83c\udfc3\u200d\u2640\ufe0f",
                "\ud83d\udc83",
                "\ud83d\udd7a",
                "\ud83d\udd74",
                "\ud83d\udc6f",
                "\ud83d\udc6f\u200d\u2642\ufe0f",
                "\ud83d\udc6f\u200d\u2640\ufe0f",
                "\ud83e\uddd6",
                "\ud83e\uddd6\u200d\u2642\ufe0f",
                "\ud83e\uddd6\u200d\u2640\ufe0f",
                "\ud83e\uddd8",
                "\ud83d\udc6d",
                "\ud83d\udc6b",
                "\ud83d\udc6c",
                "\ud83d\udc8f",
                "\ud83d\udc68\u200d\u2764\ufe0f\u200d\ud83d\udc8b\u200d\ud83d\udc68",
                "\ud83d\udc69\u200d\u2764\ufe0f\u200d\ud83d\udc8b\u200d\ud83d\udc69",
                "\ud83d\udc91",
                "\ud83d\udc68\u200d\u2764\ufe0f\u200d\ud83d\udc68",
                "\ud83d\udc69\u200d\u2764\ufe0f\u200d\ud83d\udc69",
                "\ud83d\udc6a",
                "\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67",
                "\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc66\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc67",
                "\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc67",
                "\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc67\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc66\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc68\u200d\ud83d\udc67\u200d\ud83d\udc67",
                "\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc66",
                "\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc67",
                "\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc66",
                "\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc66\u200d\ud83d\udc66",
                "\ud83d\udc69\u200d\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc67",
                "\ud83d\udc68\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc66\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc67",
                "\ud83d\udc68\u200d\ud83d\udc67\u200d\ud83d\udc66",
                "\ud83d\udc68\u200d\ud83d\udc67\u200d\ud83d\udc67",
                "\ud83d\udc69\u200d\ud83d\udc66",
                "\ud83d\udc69\u200d\ud83d\udc66\u200d\ud83d\udc66",
                "\ud83d\udc69\u200d\ud83d\udc67",
                "\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc66",
                "\ud83d\udc69\u200d\ud83d\udc67\u200d\ud83d\udc67",
                "\ud83d\udde3",
                "\ud83d\udc64",
                "\ud83d\udc65",
                "\ud83d\udc63",
                "\ud83e\uddf3",
                "\ud83c\udf02",
                "\u2602",
                "\ud83e\uddf5",
                "\ud83e\uddf6",
                "\ud83d\udc53",
                "\ud83d\udd76",
                "\ud83e\udd7d",
                "\ud83e\udd7c",
                "\ud83d\udc54",
                "\ud83d\udc55",
                "\ud83d\udc56",
                "\ud83e\udde3",
                "\ud83e\udde4",
                "\ud83e\udde5",
                "\ud83e\udde6",
                "\ud83d\udc57",
                "\ud83d\udc58",
                "\ud83d\udc59",
                "\ud83d\udc5a",
                "\ud83d\udc5b",
                "\ud83d\udc5c",
                "\ud83d\udc5d",
                "\ud83c\udf92",
                "\ud83d\udc5e",
                "\ud83d\udc5f",
                "\ud83e\udd7e",
                "\ud83e\udd7f",
                "\ud83d\udc60",
                "\ud83d\udc61",
                "\ud83d\udc62",
                "\ud83d\udc51",
                "\ud83d\udc52",
                "\ud83c\udfa9",
                "\ud83c\udf93",
                "\ud83e\udde2",
                "\u26d1",
                "\ud83d\udc84",
                "\ud83d\udc8d",
                "\ud83d\udcbc"
        };
        String[] means = new String[] {
                "Grinning Face",
                "Grinning Face With Big Eyes",
                "Grinning Face With Smiling Eyes",
                "Beaming Face With Smiling Eyes",
                "Grinning Squinting Face",
                "Grinning Face With Sweat",
                "Rolling on the Floor Laughing",
                "Face With Tears of Joy",
                "Slightly Smiling Face",
                "Upside-Down Face",
                "Winking Face",
                "Smiling Face With Smiling Eyes",
                "Smiling Face With Halo",
                "Smiling Face With Hearts",
                "Smiling Face With Heart-Eyes",
                "Star-Struck",
                "Face Blowing a Kiss",
                "Kissing Face",
                "Smiling Face",
                "Kissing Face With Closed Eyes",
                "Kissing Face With Smiling Eyes",
                "Face Savoring Food",
                "Face With Tongue",
                "Winking Face With Tongue",
                "Zany Face",
                "Squinting Face With Tongue",
                "Money-Mouth Face",
                "Hugging Face",
                "Face With Hand Over Mouth",
                "Shushing Face",
                "Thinking Face",
                "Zipper-Mouth Face",
                "Face With Raised Eyebrow",
                "Neutral Face",
                "Expressionless Face",
                "Face Without Mouth",
                "Smirking Face",
                "Unamused Face",
                "Face With Rolling Eyes",
                "Grimacing Face",
                "Lying Face",
                "Relieved Face",
                "Pensive Face",
                "Sleepy Face",
                "Drooling Face",
                "Sleeping Face",
                "Face With Medical Mask",
                "Face With Thermometer",
                "Face With Head-Bandage",
                "Nauseated Face",
                "Face Vomiting",
                "Sneezing Face",
                "Hot Face",
                "Cold Face",
                "Woozy Face",
                "Dizzy Face",
                "Exploding Head",
                "Cowboy Hat Face",
                "Partying Face",
                "Smiling Face With Sunglasses",
                "Nerd Face",
                "Face With Monocle",
                "Confused Face",
                "Worried Face",
                "Slightly Frowning Face",
                "Frowning Face",
                "Face With Open Mouth",
                "Hushed Face",
                "Astonished Face",
                "Flushed Face",
                "Pleading Face",
                "Frowning Face With Open Mouth",
                "Anguished Face",
                "Fearful Face",
                "Anxious Face With Sweat",
                "Sad but Relieved Face",
                "Crying Face",
                "Loudly Crying Face",
                "Face Screaming in Fear",
                "Confounded Face",
                "Persevering Face",
                "Disappointed Face",
                "Downcast Face With Sweat",
                "Weary Face",
                "Tired Face",
                "Face With Steam From Nose",
                "Pouting Face",
                "Angry Face",
                "Face With Symbols on Mouth",
                "Smiling Face With Horns",
                "Angry Face With Horns",
                "Skull",
                "Skull and Crossbones",
                "Pile of Poo",
                "Clown Face",
                "Ogre",
                "Goblin",
                "Ghost",
                "Alien",
                "Alien Monster",
                "Robot",
                "Grinning Cat",
                "Grinning Cat With Smiling Eyes",
                "Cat With Tears of Joy",
                "Smiling Cat With Heart-Eyes",
                "Cat With Wry Smile",
                "Kissing Cat",
                "Weary Cat",
                "Crying Cat",
                "Pouting Cat",
                "Kiss Mark",
                "Waving Hand",
                "Raised Back of Hand",
                "Hand With Fingers Splayed",
                "Raised Hand",
                "Vulcan Salute",
                "OK Hand",
                "Victory Hand",
                "Crossed Fingers",
                "Love-You Gesture",
                "Sign of the Horns",
                "Call Me Hand",
                "Backhand Index Pointing Left",
                "Backhand Index Pointing Right",
                "Backhand Index Pointing Up",
                "Middle Finger",
                "Backhand Index Pointing Down",
                "Index Pointing Up",
                "Thumbs Up",
                "Thumbs Down",
                "Raised Fist",
                "Oncoming Fist",
                "Left-Facing Fist",
                "Right-Facing Fist",
                "Clapping Hands",
                "Raising Hands",
                "Open Hands",
                "Palms Up Together",
                "Handshake",
                "Folded Hands",
                "Writing Hand",
                "Nail Polish",
                "Selfie",
                "Flexed Biceps",
                "Leg",
                "Foot",
                "Ear",
                "Nose",
                "Brain",
                "Tooth",
                "Bone",
                "Eyes",
                "Eye",
                "Tongue",
                "Mouth",
                "Baby",
                "Child",
                "Boy",
                "Girl",
                "Person",
                "Person: Blond Hair",
                "Man",
                "Man: Beard",
                "Man: Red Hair",
                "Man: Curly Hair",
                "Man: White Hair",
                "Man: Bald",
                "Woman",
                "Woman: Red Hair",
                "Woman: Curly Hair",
                "Woman: White Hair",
                "Woman: Bald",
                "Woman: Blond Hair",
                "Man: Blond Hair",
                "Older Person",
                "Old Man",
                "Old Woman",
                "Person Frowning",
                "Man Frowning",
                "Woman Frowning",
                "Person Pouting",
                "Man Pouting",
                "Woman Pouting",
                "Person Gesturing No",
                "Man Gesturing No",
                "Woman Gesturing No",
                "Person Gesturing OK",
                "Man Gesturing OK",
                "Woman Gesturing OK",
                "Person Tipping Hand",
                "Man Tipping Hand",
                "Woman Tipping Hand",
                "Person Raising Hand",
                "Man Raising Hand",
                "Woman Raising Hand",
                "Person Bowing",
                "Man Bowing",
                "Woman Bowing",
                "Person Facepalming",
                "Man Facepalming",
                "Woman Facepalming",
                "Person Shrugging",
                "Man Shrugging",
                "Woman Shrugging",
                "Man Health Worker",
                "Woman Health Worker",
                "Man Student",
                "Woman Student",
                "Man Teacher",
                "Woman Teacher",
                "Man Judge",
                "Woman Judge",
                "Man Farmer",
                "Woman Farmer",
                "Man Cook",
                "Woman Cook",
                "Man Mechanic",
                "Woman Mechanic",
                "Man Factory Worker",
                "Woman Factory Worker",
                "Man Office Worker",
                "Woman Office Worker",
                "Man Scientist",
                "Woman Scientist",
                "Man Technologist",
                "Woman Technologist",
                "Man Singer",
                "Woman Singer",
                "Man Artist",
                "Woman Artist",
                "Man Pilot",
                "Woman Pilot",
                "Man Astronaut",
                "Woman Astronaut",
                "Man Firefighter",
                "Woman Firefighter",
                "Police Officer",
                "Man Police Officer",
                "Woman Police Officer",
                "Detective",
                "Man Detective",
                "Woman Detective",
                "Guard",
                "Man Guard",
                "Woman Guard",
                "Construction Worker",
                "Man Construction Worker",
                "Woman Construction Worker",
                "Prince",
                "Princess",
                "Person Wearing Turban",
                "Man Wearing Turban",
                "Woman Wearing Turban",
                "Man With Skullcap",
                "Woman With Headscarf",
                "Man in Tuxedo",
                "Bride With Veil",
                "Pregnant Woman",
                "Breast-Feeding",
                "Baby Angel",
                "Santa Claus",
                "Mrs. Claus",
                "Superhero",
                "Man Superhero",
                "Woman Superhero",
                "Supervillain",
                "Man Supervillain",
                "Woman Supervillain",
                "Mage",
                "Man Mage",
                "Woman Mage",
                "Fairy",
                "Man Fairy",
                "Woman Fairy",
                "Vampire",
                "Man Vampire",
                "Woman Vampire",
                "Merperson",
                "Merman",
                "Mermaid",
                "Elf",
                "Man Elf",
                "Woman Elf",
                "Genie",
                "Man Genie",
                "Woman Genie",
                "Zombie",
                "Man Zombie",
                "Woman Zombie",
                "Person Getting Massage",
                "Man Getting Massage",
                "Woman Getting Massage",
                "Person Getting Haircut",
                "Man Getting Haircut",
                "Woman Getting Haircut",
                "Person Walking",
                "Man Walking",
                "Woman Walking",
                "Person Running",
                "Man Running",
                "Woman Running",
                "Woman Dancing",
                "Man Dancing",
                "Man in Suit Levitating",
                "People With Bunny Ears",
                "Men With Bunny Ears",
                "Women With Bunny Ears",
                "Person in Steamy Room",
                "Man in Steamy Room",
                "Woman in Steamy Room",
                "Person in Lotus Position",
                "Women Holding Hands",
                "Woman and Man Holding Hands",
                "Men Holding Hands",
                "Kiss",
                "Kiss: Man, Man",
                "Kiss: Woman, Woman",
                "Couple With Heart",
                "Couple With Heart: Man, Man",
                "Couple With Heart: Woman, Woman",
                "Family",
                "Family: Man, Woman, Boy",
                "Family: Man, Woman, Girl",
                "Family: Man, Woman, Girl, Boy",
                "Family: Man, Woman, Boy, Boy",
                "Family: Man, Woman, Girl, Girl",
                "Family: Man, Man, Boy",
                "Family: Man, Man, Girl",
                "Family: Man, Man, Girl, Boy",
                "Family: Man, Man, Boy, Boy",
                "Family: Man, Man, Girl, Girl",
                "Family: Woman, Woman, Boy",
                "Family: Woman, Woman, Girl",
                "Family: Woman, Woman, Girl, Boy",
                "Family: Woman, Woman, Boy, Boy",
                "Family: Woman, Woman, Girl, Girl",
                "Family: Man, Boy",
                "Family: Man, Boy, Boy",
                "Family: Man, Girl",
                "Family: Man, Girl, Boy",
                "Family: Man, Girl, Girl",
                "Family: Woman, Boy",
                "Family: Woman, Boy, Boy",
                "Family: Woman, Girl",
                "Family: Woman, Girl, Boy",
                "Family: Woman, Girl, Girl",
                "Speaking Head",
                "Bust in Silhouette",
                "Busts in Silhouette",
                "Footprints",
                "Luggage",
                "Closed Umbrella",
                "Umbrella",
                "Thread",
                "Yarn",
                "Glasses",
                "Sunglasses",
                "Goggles",
                "Lab Coat",
                "Necktie",
                "T-Shirt",
                "Jeans",
                "Scarf",
                "Gloves",
                "Coat",
                "Socks",
                "Dress",
                "Kimono",
                "Bikini",
                "Woman’s Clothes",
                "Purse",
                "Handbag",
                "Clutch Bag",
                "Backpack",
                "Man’s Shoe",
                "Running Shoe",
                "Hiking Boot",
                "Flat Shoe",
                "High-Heeled Shoe",
                "Woman’s Sandal",
                "Woman’s Boot",
                "Crown",
                "Woman’s Hat",
                "Top Hat",
                "Graduation Cap",
                "Billed Cap",
                "Rescue Worker’s Helmet",
                "Lipstick",
                "Ring",
                "Briefcase",
        };
        HashMap<String, String> emoji = new HashMap<>();
        for (int i = 0; i < keys.length; i++) {
            emoji.put(keys[i], means[i]);
        }
        return emoji;
    }
}
